### ISSUE TITLE
how to switch to libusb backend?

### ISSUE THREAD

**Issue by rajiv-obhcare** [sstallion/go-hid#3]
It appears like by default the package is using the `hidraw` backend, how do I switch to `libusb` ?

**Comment by sstallion** [comment]
Hi @rajiv-obhcare - there is some preliminary support using build flags, however I haven't had much time to test it on Linux yet. You should be able to install with libusb support with the following:
```
$ go install -tags libusb github.com/sstallion/go-hid
```
Let me know how things go - if there are any issues and you're willing to help test, I can apply fixes and create a new release for you.

**Comment by sstallion** [comment]
I had a bit of time to take a look into supporting libusb this evening. A few changes were needed to link against libusb, but for the most part it seemed to "just work". I've also updated CI to ensure that libusb support is verified on each push going forward. When you get a moment, please try the 0.13.3 release. You'll need to specify the `libusb` build constraint when building your application in order to enable backend support:
```
$ go build -tags libusb ./...
```
Cheers!
